universe = vanilla
executable = /nfshome/store03/users/georgia.stevens/gwdata/realdata/graphs.py
arguments = " $(Process) "
log = /nfshome/store03/users/georgia.stevens/gwdata/realdata/script.log
output = /nfshome/store03/users/georgia.stevens/gwdata/realdata/output.txt
error = /nfshome/store03/users/georgia.stevens/gwdata/realdata/script.err
accounting_group_user = georgia.stevens
accounting_group = aluk.dev.o2.burst.explore.test.
getenv = True
notification = Never
queue 1
