from ringdown import RingdownTemplateBank
from matplotlib import pyplot as plt
import numpy as np

frange = [1000, 3000]  # frequency range (Hz)
qrange = [3, 20]  # Quality factor ranges
taurange = [0.05,0.5]

mm = 0.03  # maximum mismatch

tb = RingdownTemplateBank(frange, taurange=taurange, mm=mm)

print("Number of templates is {}".format(len(tb)))

taubank = np.array(tb.bank_taus)
print(len(taubank))
taubank = taubank[taubank < 0.5]
print(len(taubank))
calc
print()


plt.plot(tb.bank_freqs, tb.bank_taus, '.', color="lightskyblue", ls="None")
plt.xlabel("Frequency (Hz)")
plt.ylabel("Damping Time (s)")
plt.title('Templates Generated by the Ring-down Template Bank')
plt.show()
plt.savefig('TemplateBank39494templates.png')
