universe = vanilla
executable = /nfshome/store03/users/georgia.stevens/scripts/matchedfiltersignals2/matchedfiltersignals.py
arguments = " $(Process) "
log = /nfshome/store03/users/georgia.stevens/scripts/matchedfiltersignals2/script.log
output = /nfshome/store03/users/georgia.stevens/scripts/matchedfiltersignals2/output.txt
error = /nfshome/store03/users/georgia.stevens/scripts/matchedfiltersignals2/script.err
accounting_group_user = georgia.stevens
accounting_group = aluk.dev.o2.burst.explore.test.
getenv = True
notification = Never
queue 1000

